import type { AIProvider } from "@/lib/types";

export const ALLOWED_AI_PROVIDERS: Omit<AIProvider, "workspaceId">[] = [
  {
    id: "anthropic",
    name: "Anthropic",
    slug: "anthropic",
    apiKey: "sk-ant-****",
    enabled: true,
    models: [
      { id: "claude-sonnet-4-0", name: "Claude 4 Sonnet", maxTokens: 200000 },
      { id: "claude-sonnet-4-0-1m", name: "Claude 4 Sonnet 1M", maxTokens: 1000000 },
      { id: "claude-haiku-4-5", name: "Claude 4.5 Haiku", maxTokens: 200000 },
      { id: "claude-opus-4-5", name: "Claude 4.5 Opus", maxTokens: 200000 },
      { id: "claude-sonnet-4-5", name: "Claude 4.5 Sonnet", maxTokens: 1000000 },
      { id: "claude-opus-4-6", name: "Claude 4.6 Opus", maxTokens: 1000000 },
      { id: "claude-opus-4-6-fast", name: "Claude 4.6 Opus (Fast mode)", maxTokens: 1000000 },
      { id: "claude-sonnet-4-6", name: "Claude 4.6 Sonnet", maxTokens: 1000000 },
    ],
  },
  {
    id: "cursor",
    name: "Cursor",
    slug: "cursor",
    apiKey: "",
    enabled: true,
    models: [
      { id: "composer-1", name: "Composer 1", maxTokens: 200000 },
      { id: "composer-1.5", name: "Composer 1.5", maxTokens: 200000 },
    ],
  },
  {
    id: "google",
    name: "Google",
    slug: "google",
    apiKey: "",
    enabled: true,
    models: [
      { id: "gemini-2.5-flash", name: "Gemini 2.5 Flash", maxTokens: 1000000 },
      { id: "gemini-3-flash", name: "Gemini 3 Flash", maxTokens: 1000000 },
      { id: "gemini-3-pro", name: "Gemini 3 Pro", maxTokens: 1000000 },
      { id: "gemini-3-pro-image-preview", name: "Gemini 3 Pro Image Preview", maxTokens: 1000000 },
      { id: "gemini-3.1-pro", name: "Gemini 3.1 Pro", maxTokens: 1000000 },
    ],
  },
  {
    id: "openai",
    name: "OpenAI",
    slug: "openai",
    apiKey: "sk-****",
    enabled: true,
    models: [
      { id: "gpt-5", name: "GPT-5", maxTokens: 272000 },
      { id: "gpt-5-fast", name: "GPT-5 Fast", maxTokens: 272000 },
      { id: "gpt-5-mini", name: "GPT-5 Mini", maxTokens: 272000 },
      { id: "gpt-5-codex", name: "GPT-5-Codex", maxTokens: 272000 },
      { id: "gpt-5.1-codex", name: "GPT-5.1 Codex", maxTokens: 272000 },
      { id: "gpt-5.1-codex-max", name: "GPT-5.1 Codex Max", maxTokens: 272000 },
      { id: "gpt-5.1-codex-mini", name: "GPT-5.1 Codex Mini", maxTokens: 272000 },
      { id: "gpt-5.2", name: "GPT-5.2", maxTokens: 272000 },
      { id: "gpt-5.2-codex", name: "GPT-5.2 Codex", maxTokens: 272000 },
      { id: "gpt-5.3-codex", name: "GPT-5.3 Codex", maxTokens: 272000 },
    ],
  },
  {
    id: "xai",
    name: "xAI",
    slug: "xai",
    apiKey: "",
    enabled: true,
    models: [{ id: "grok-code", name: "Grok Code", maxTokens: 256000 }],
  },
  {
    id: "moonshot",
    name: "Moonshot",
    slug: "moonshot",
    apiKey: "",
    enabled: true,
    models: [{ id: "kimi-k2.5", name: "Kimi K2.5", maxTokens: 262000 }],
  },
];
