/**
 * Curated skills from https://skills.sh/ - The Agent Skills Directory
 * Source: skills.sh leaderboard (https://skills.sh/)
 */

export interface SkillItem {
  id: string;
  name: string;
  repo: string;
  installs: string;
}

export const SKILLS_LIST: SkillItem[] = [
  {
    id: "vercel-labs/skills/find-skills",
    name: "find-skills",
    repo: "vercel-labs/skills",
    installs: "344.9K",
  },
  {
    id: "vercel-labs/agent-skills/vercel-react-best-practices",
    name: "vercel-react-best-practices",
    repo: "vercel-labs/agent-skills",
    installs: "173.7K",
  },
  {
    id: "vercel-labs/agent-skills/web-design-guidelines",
    name: "web-design-guidelines",
    repo: "vercel-labs/agent-skills",
    installs: "133.0K",
  },
  {
    id: "remotion-dev/skills/remotion-best-practices",
    name: "remotion-best-practices",
    repo: "remotion-dev/skills",
    installs: "115.3K",
  },
  {
    id: "anthropics/skills/frontend-design",
    name: "frontend-design",
    repo: "anthropics/skills",
    installs: "105.4K",
  },
  {
    id: "microsoft/github-copilot-for-azure/azure-ai",
    name: "azure-ai",
    repo: "microsoft/github-copilot-for-azure",
    installs: "81.2K",
  },
  {
    id: "microsoft/github-copilot-for-azure/azure-observability",
    name: "azure-observability",
    repo: "microsoft/github-copilot-for-azure",
    installs: "81.2K",
  },
  {
    id: "microsoft/github-copilot-for-azure/azure-cost-optimization",
    name: "azure-cost-optimization",
    repo: "microsoft/github-copilot-for-azure",
    installs: "81.1K",
  },
  {
    id: "microsoft/github-copilot-for-azure/azure-storage",
    name: "azure-storage",
    repo: "microsoft/github-copilot-for-azure",
    installs: "81.1K",
  },
  {
    id: "microsoft/github-copilot-for-azure/azure-diagnostics",
    name: "azure-diagnostics",
    repo: "microsoft/github-copilot-for-azure",
    installs: "81.1K",
  },
  {
    id: "vercel-labs/agent-browser/agent-browser",
    name: "agent-browser",
    repo: "vercel-labs/agent-browser",
    installs: "64.5K",
  },
  {
    id: "vercel-labs/agent-skills/vercel-composition-patterns",
    name: "vercel-composition-patterns",
    repo: "vercel-labs/agent-skills",
    installs: "60.5K",
  },
  {
    id: "anthropics/skills/skill-creator",
    name: "skill-creator",
    repo: "anthropics/skills",
    installs: "52.1K",
  },
  {
    id: "browser-use/browser-use/browser-use",
    name: "browser-use",
    repo: "browser-use/browser-use",
    installs: "41.3K",
  },
  {
    id: "vercel-labs/agent-skills/vercel-react-native-skills",
    name: "vercel-react-native-skills",
    repo: "vercel-labs/agent-skills",
    installs: "42.2K",
  },
  {
    id: "inference-sh-9/skills/agent-tools",
    name: "agent-tools",
    repo: "inference-sh-9/skills",
    installs: "34.7K",
  },
  {
    id: "obra/superpowers/brainstorming",
    name: "brainstorming",
    repo: "obra/superpowers",
    installs: "33.3K",
  },
  {
    id: "supabase/agent-skills/supabase-postgres-best-practices",
    name: "supabase-postgres-best-practices",
    repo: "supabase/agent-skills",
    installs: "25.2K",
  },
  { id: "anthropics/skills/pdf", name: "pdf", repo: "anthropics/skills", installs: "23.3K" },
  {
    id: "vercel-labs/next-skills/next-best-practices",
    name: "next-best-practices",
    repo: "vercel-labs/next-skills",
    installs: "22.3K",
  },
  { id: "anthropics/skills/pptx", name: "pptx", repo: "anthropics/skills", installs: "19.5K" },
  {
    id: "obra/superpowers/systematic-debugging",
    name: "systematic-debugging",
    repo: "obra/superpowers",
    installs: "18.2K",
  },
  { id: "anthropics/skills/docx", name: "docx", repo: "anthropics/skills", installs: "17.8K" },
  { id: "anthropics/skills/xlsx", name: "xlsx", repo: "anthropics/skills", installs: "17.1K" },
  {
    id: "better-auth/skills/better-auth-best-practices",
    name: "better-auth-best-practices",
    repo: "better-auth/skills",
    installs: "16.2K",
  },
  {
    id: "anthropics/skills/webapp-testing",
    name: "webapp-testing",
    repo: "anthropics/skills",
    installs: "15.6K",
  },
  {
    id: "obra/superpowers/test-driven-development",
    name: "test-driven-development",
    repo: "obra/superpowers",
    installs: "14.9K",
  },
  {
    id: "anthropics/skills/mcp-builder",
    name: "mcp-builder",
    repo: "anthropics/skills",
    installs: "13.9K",
  },
  {
    id: "obra/superpowers/executing-plans",
    name: "executing-plans",
    repo: "obra/superpowers",
    installs: "13.9K",
  },
  {
    id: "expo/skills/building-native-ui",
    name: "building-native-ui",
    repo: "expo/skills",
    installs: "13.5K",
  },
  {
    id: "obra/superpowers/requesting-code-review",
    name: "requesting-code-review",
    repo: "obra/superpowers",
    installs: "13.1K",
  },
  {
    id: "wshobson/agents/tailwind-design-system",
    name: "tailwind-design-system",
    repo: "wshobson/agents",
    installs: "11.9K",
  },
  {
    id: "anthropics/skills/canvas-design",
    name: "canvas-design",
    repo: "anthropics/skills",
    installs: "11.9K",
  },
  {
    id: "obra/superpowers/subagent-driven-development",
    name: "subagent-driven-development",
    repo: "obra/superpowers",
    installs: "11.1K",
  },
  {
    id: "expo/skills/native-data-fetching",
    name: "native-data-fetching",
    repo: "expo/skills",
    installs: "8.7K",
  },
  {
    id: "expo/skills/upgrading-expo",
    name: "upgrading-expo",
    repo: "expo/skills",
    installs: "8.5K",
  },
  {
    id: "anthropics/skills/template-skill",
    name: "template-skill",
    repo: "anthropics/skills",
    installs: "8.2K",
  },
  { id: "vercel/ai/ai-sdk", name: "ai-sdk", repo: "vercel/ai", installs: "7.5K" },
  {
    id: "vercel/turborepo/turborepo",
    name: "turborepo",
    repo: "vercel/turborepo",
    installs: "7.3K",
  },
  { id: "antfu/skills/vite", name: "vite", repo: "antfu/skills", installs: "7.2K" },
  {
    id: "better-auth/skills/create-auth-skill",
    name: "create-auth-skill",
    repo: "better-auth/skills",
    installs: "6.5K",
  },
  { id: "firecrawl/cli/firecrawl", name: "firecrawl", repo: "firecrawl/cli", installs: "6.5K" },
  { id: "antfu/skills/vitest", name: "vitest", repo: "antfu/skills", installs: "6.5K" },
  {
    id: "callstackincubator/agent-skills/react-native-best-practices",
    name: "react-native-best-practices",
    repo: "callstackincubator/agent-skills",
    installs: "6.4K",
  },
  {
    id: "vercel-labs/next-skills/next-cache-components",
    name: "next-cache-components",
    repo: "vercel-labs/next-skills",
    installs: "6.2K",
  },
  { id: "antfu/skills/vue", name: "vue", repo: "antfu/skills", installs: "6.2K" },
  {
    id: "wshobson/agents/architecture-patterns",
    name: "architecture-patterns",
    repo: "wshobson/agents",
    installs: "5.9K",
  },
  {
    id: "wshobson/agents/nextjs-app-router-patterns",
    name: "nextjs-app-router-patterns",
    repo: "wshobson/agents",
    installs: "5.9K",
  },
  {
    id: "kadajett/agent-nestjs-skills/nestjs-best-practices",
    name: "nestjs-best-practices",
    repo: "kadajett/agent-nestjs-skills",
    installs: "5.1K",
  },
  {
    id: "millionco/react-doctor/react-doctor",
    name: "react-doctor",
    repo: "millionco/react-doctor",
    installs: "5.0K",
  },
  {
    id: "wshobson/agents/prompt-engineering-patterns",
    name: "prompt-engineering-patterns",
    repo: "wshobson/agents",
    installs: "5.3K",
  },
  {
    id: "wshobson/agents/postgresql-table-design",
    name: "postgresql-table-design",
    repo: "wshobson/agents",
    installs: "5.2K",
  },
  {
    id: "wshobson/agents/python-testing-patterns",
    name: "python-testing-patterns",
    repo: "wshobson/agents",
    installs: "5.2K",
  },
  {
    id: "obra/episodic-memory/remembering-conversations",
    name: "remembering-conversations",
    repo: "obra/episodic-memory",
    installs: "5.5K",
  },
  {
    id: "antfu/skills/vue-best-practices",
    name: "vue-best-practices",
    repo: "antfu/skills",
    installs: "5.4K",
  },
  {
    id: "wshobson/agents/code-review-excellence",
    name: "code-review-excellence",
    repo: "wshobson/agents",
    installs: "5.5K",
  },
  { id: "antfu/skills/pnpm", name: "pnpm", repo: "antfu/skills", installs: "4.8K" },
  {
    id: "antfu/skills/vueuse-functions",
    name: "vueuse-functions",
    repo: "antfu/skills",
    installs: "4.8K",
  },
  {
    id: "wshobson/agents/responsive-design",
    name: "responsive-design",
    repo: "wshobson/agents",
    installs: "4.7K",
  },
  { id: "antfu/skills/pinia", name: "pinia", repo: "antfu/skills", installs: "4.7K" },
  { id: "antfu/skills/nuxt", name: "nuxt", repo: "antfu/skills", installs: "4.4K" },
  {
    id: "antfu/skills/web-design-guidelines",
    name: "web-design-guidelines",
    repo: "antfu/skills",
    installs: "4.4K",
  },
  { id: "mastra-ai/skills/mastra", name: "mastra", repo: "mastra-ai/skills", installs: "4.4K" },
  {
    id: "wshobson/agents/e2e-testing-patterns",
    name: "e2e-testing-patterns",
    repo: "wshobson/agents",
    installs: "4.3K",
  },
  {
    id: "wshobson/agents/error-handling-patterns",
    name: "error-handling-patterns",
    repo: "wshobson/agents",
    installs: "4.3K",
  },
  { id: "antfu/skills/vitepress", name: "vitepress", repo: "antfu/skills", installs: "3.6K" },
  {
    id: "wshobson/agents/sql-optimization-patterns",
    name: "sql-optimization-patterns",
    repo: "wshobson/agents",
    installs: "3.9K",
  },
  {
    id: "wshobson/agents/github-actions-templates",
    name: "github-actions-templates",
    repo: "wshobson/agents",
    installs: "3.8K",
  },
  {
    id: "wshobson/agents/javascript-testing-patterns",
    name: "javascript-testing-patterns",
    repo: "wshobson/agents",
    installs: "3.6K",
  },
  {
    id: "squirrelscan/skills/audit-website",
    name: "audit-website",
    repo: "squirrelscan/skills",
    installs: "28.0K",
  },
  {
    id: "coreyhaines31/marketingskills/seo-audit",
    name: "seo-audit",
    repo: "coreyhaines31/marketingskills",
    installs: "28.3K",
  },
  {
    id: "coreyhaines31/marketingskills/copywriting",
    name: "copywriting",
    repo: "coreyhaines31/marketingskills",
    installs: "21.7K",
  },
  {
    id: "obra/superpowers/writing-plans",
    name: "writing-plans",
    repo: "obra/superpowers",
    installs: "16.4K",
  },
  {
    id: "obra/superpowers/using-superpowers",
    name: "using-superpowers",
    repo: "obra/superpowers",
    installs: "12.5K",
  },
  {
    id: "obra/superpowers/writing-skills",
    name: "writing-skills",
    repo: "obra/superpowers",
    installs: "10.2K",
  },
  {
    id: "obra/superpowers/verification-before-completion",
    name: "verification-before-completion",
    repo: "obra/superpowers",
    installs: "10.6K",
  },
  {
    id: "obra/superpowers/receiving-code-review",
    name: "receiving-code-review",
    repo: "obra/superpowers",
    installs: "10.7K",
  },
  {
    id: "obra/superpowers/dispatching-parallel-agents",
    name: "dispatching-parallel-agents",
    repo: "obra/superpowers",
    installs: "9.7K",
  },
  {
    id: "obra/superpowers/finishing-a-development-branch",
    name: "finishing-a-development-branch",
    repo: "obra/superpowers",
    installs: "8.9K",
  },
  {
    id: "obra/superpowers/using-git-worktrees",
    name: "using-git-worktrees",
    repo: "obra/superpowers",
    installs: "10.3K",
  },
  {
    id: "wshobson/agents/nodejs-backend-patterns",
    name: "nodejs-backend-patterns",
    repo: "wshobson/agents",
    installs: "6.5K",
  },
  {
    id: "wshobson/agents/python-performance-optimization",
    name: "python-performance-optimization",
    repo: "wshobson/agents",
    installs: "6.4K",
  },
  {
    id: "wshobson/agents/api-design-principles",
    name: "api-design-principles",
    repo: "wshobson/agents",
    installs: "7.2K",
  },
  {
    id: "wshobson/agents/fastapi-templates",
    name: "fastapi-templates",
    repo: "wshobson/agents",
    installs: "4.7K",
  },
  {
    id: "wshobson/agents/async-python-patterns",
    name: "async-python-patterns",
    repo: "wshobson/agents",
    installs: "4.2K",
  },
  {
    id: "wshobson/agents/security-requirement-extraction",
    name: "security-requirement-extraction",
    repo: "wshobson/agents",
    installs: "3.9K",
  },
  {
    id: "wshobson/agents/mobile-ios-design",
    name: "mobile-ios-design",
    repo: "wshobson/agents",
    installs: "4.3K",
  },
  {
    id: "wshobson/agents/mobile-android-design",
    name: "mobile-android-design",
    repo: "wshobson/agents",
    installs: "3.7K",
  },
  {
    id: "expo/skills/expo-dev-client",
    name: "expo-dev-client",
    repo: "expo/skills",
    installs: "7.5K",
  },
  {
    id: "expo/skills/expo-deployment",
    name: "expo-deployment",
    repo: "expo/skills",
    installs: "7.5K",
  },
  {
    id: "expo/skills/expo-tailwind-setup",
    name: "expo-tailwind-setup",
    repo: "expo/skills",
    installs: "7.3K",
  },
  {
    id: "expo/skills/expo-api-routes",
    name: "expo-api-routes",
    repo: "expo/skills",
    installs: "6.6K",
  },
  {
    id: "expo/skills/expo-cicd-workflows",
    name: "expo-cicd-workflows",
    repo: "expo/skills",
    installs: "6.3K",
  },
  { id: "expo/skills/use-dom", name: "use-dom", repo: "expo/skills", installs: "5.6K" },
  {
    id: "vercel-labs/next-skills/next-upgrade",
    name: "next-upgrade",
    repo: "vercel-labs/next-skills",
    installs: "4.1K",
  },
  {
    id: "anthropics/skills/brand-guidelines",
    name: "brand-guidelines",
    repo: "anthropics/skills",
    installs: "8.8K",
  },
  {
    id: "anthropics/skills/internal-comms",
    name: "internal-comms",
    repo: "anthropics/skills",
    installs: "8.1K",
  },
  {
    id: "anthropics/skills/theme-factory",
    name: "theme-factory",
    repo: "anthropics/skills",
    installs: "9.7K",
  },
  {
    id: "anthropics/skills/web-artifacts-builder",
    name: "web-artifacts-builder",
    repo: "anthropics/skills",
    installs: "9.3K",
  },
  {
    id: "anthropics/skills/algorithmic-art",
    name: "algorithmic-art",
    repo: "anthropics/skills",
    installs: "10.0K",
  },
  {
    id: "anthropics/skills/doc-coauthoring",
    name: "doc-coauthoring",
    repo: "anthropics/skills",
    installs: "9.9K",
  },
  {
    id: "anthropics/skills/slack-gif-creator",
    name: "slack-gif-creator",
    repo: "anthropics/skills",
    installs: "7.6K",
  },
  {
    id: "inference-sh-9/skills/ai-image-generation",
    name: "ai-image-generation",
    repo: "inference-sh-9/skills",
    installs: "32.2K",
  },
  {
    id: "inference-sh-9/skills/ai-video-generation",
    name: "ai-video-generation",
    repo: "inference-sh-9/skills",
    installs: "31.9K",
  },
  {
    id: "inference-sh-9/skills/web-search",
    name: "web-search",
    repo: "inference-sh-9/skills",
    installs: "4.8K",
  },
  {
    id: "inference-sh-9/skills/python-executor",
    name: "python-executor",
    repo: "inference-sh-9/skills",
    installs: "4.7K",
  },
  {
    id: "inference-sh-9/skills/python-sdk",
    name: "python-sdk",
    repo: "inference-sh-9/skills",
    installs: "4.6K",
  },
  {
    id: "inference-sh-9/skills/javascript-sdk",
    name: "javascript-sdk",
    repo: "inference-sh-9/skills",
    installs: "4.5K",
  },
  {
    id: "giuseppe-trisciuoglio/developer-kit/shadcn-ui",
    name: "shadcn-ui",
    repo: "giuseppe-trisciuoglio/developer-kit",
    installs: "7.8K",
  },
  {
    id: "google-labs-code/stitch-skills/shadcn-ui",
    name: "shadcn-ui",
    repo: "google-labs-code/stitch-skills",
    installs: "6.4K",
  },
  {
    id: "nextlevelbuilder/ui-ux-pro-max-skill/ui-ux-pro-max",
    name: "ui-ux-pro-max",
    repo: "nextlevelbuilder/ui-ux-pro-max-skill",
    installs: "40.8K",
  },
  {
    id: "hyf0/vue-skills/vue-debug-guides",
    name: "vue-debug-guides",
    repo: "hyf0/vue-skills",
    installs: "7.5K",
  },
  {
    id: "hyf0/vue-skills/vue-best-practices",
    name: "vue-best-practices",
    repo: "hyf0/vue-skills",
    installs: "7.4K",
  },
  {
    id: "dammyjay93/interface-design/interface-design",
    name: "interface-design",
    repo: "dammyjay93/interface-design",
    installs: "5.8K",
  },
  {
    id: "avdlee/swiftui-agent-skill/swiftui-expert-skill",
    name: "swiftui-expert-skill",
    repo: "avdlee/swiftui-agent-skill",
    installs: "5.9K",
  },
  {
    id: "madteacher/mad-agents-skills/flutter-animations",
    name: "flutter-animations",
    repo: "madteacher/mad-agents-skills",
    installs: "8.0K",
  },
  {
    id: "jeffallan/claude-skills/golang-pro",
    name: "golang-pro",
    repo: "jeffallan/claude-skills",
    installs: "3.6K",
  },
  {
    id: "waynesutton/convexskills/convex",
    name: "convex",
    repo: "waynesutton/convexskills",
    installs: "3.8K",
  },
  {
    id: "sickn33/antigravity-awesome-skills/docker-expert",
    name: "docker-expert",
    repo: "sickn33/antigravity-awesome-skills",
    installs: "4.1K",
  },
  {
    id: "othmanadi/planning-with-files/planning-with-files",
    name: "planning-with-files",
    repo: "othmanadi/planning-with-files",
    installs: "4.1K",
  },
];

export function searchSkills(query: string, limit = 50): SkillItem[] {
  const q = query.trim().toLowerCase();
  if (!q) return SKILLS_LIST.slice(0, limit);
  const terms = q.split(/\s+/);
  return SKILLS_LIST.filter((skill) => {
    const searchText = `${skill.name} ${skill.repo} ${skill.id}`.toLowerCase();
    return terms.every((t) => searchText.includes(t));
  }).slice(0, limit);
}
